### ISSUE TITLE
您好，小白请教一下，这个文件是需要自己建立的吗？

### ISSUE THREAD

**Issue by SilaLiu** [jason-li-831202/Vehicle-CV-ADAS#14]
if __name__ == '__main__':
	onnx_model_path = "./ObjectDetector/models/yolov8m-coco.onnx"
	trt_model_path = "./ObjectDetector/models/yolov8m-coco.trt"

我运行python3 convertOnnxToTensorRT.py 的时候报一下错误。

File=[ ./ObjectDetector/models/yolov8m-coco.onnx ] is not exist. Please check it !

**Comment by jason-li-831202** [comment]
model下載可以參考以下issue : 
https://github.com/jason-li-831202/Vehicle-CV-ADAS/issues/1#issuecomment-1432452737
