### ISSUE TITLE
python demo.py

### ISSUE THREAD

**Issue by 1623021453** [jason-li-831202/Vehicle-CV-ADAS#17]
您好！请问运行python demo.py 终端有以下输出，没有报错，但是文件夹下保存的视频只有1k，
[2023-12-28 15:49:45] [INFO] [Pycuda] Cuda Version: (11, 4, 0)
[2023-12-28 15:49:45] [INFO] [Driver] Cuda Version: 12020
[2023-12-28 15:49:45] [INFO] UfldDetector Model Type : UFLDV2_CULANE

**Comment by TJW-XMUT** [comment]
> 您好！请问运行python demo.py 终端有以下输出，没有报错，但是文件夹下保存的视频只有1k， [2023-12-28 15:49:45] [INFO] [Pycuda] Cuda Version: (11, 4, 0) [2023-12-28 15:49:45] [INFO] [Driver] Cuda Version: 12020 [2023-12-28 15:49:45] [INFO] UfldDetector Model Type : UFLDV2_CULANE

这个问题解决了吗， 我也遇到相同的问题

**Comment by 1623021453** [comment]
解决了，我的是因为cuda版本和pytorch版本不匹配导致的，确保版本匹配就好了

**Comment by 1623021453** [comment]
解决了，我的是因为cuda版本和pytorch版本不匹配导致的，确保版本匹配就好了

**Comment by jason-li-831202** [comment]
For related questions, please refer to https://github.com/jason-li-831202/Vehicle-CV-ADAS/issues/18#issuecomment-2177950637
