### ISSUE TITLE
运行demo.py报错

### ISSUE THREAD

**Issue by 1623021453** [jason-li-831202/Vehicle-CV-ADAS#18]
运行onnx模型可以正常运行，运行trt模型，直接中断，输出如下
[2024-01-17 10:25:43] [INFO] [Pycuda] Cuda Version: (11, 4, 0)
[2024-01-17 10:25:43] [INFO] [Driver] Cuda Version: 12020
[2024-01-17 10:25:43] [INFO] ----------------------------------------
[2024-01-17 10:25:43] [INFO] UfldDetector Model Type : UFLDV2_CULANE

**Comment by 1623021453** [comment]
trt模型是用本工程中的代码转的，请问有人知道是什么原因吗？困扰了我好久

**Comment by 1623021453** [comment]
是适配的，我的cuda版本是11.4，tensorrt的版本8.2 8.4 8.6都有试过，都是会直接中断



---原始邮件---
发件人: "Kai Chun, ***@***.***&gt;
发送时间: 2024年1月17日(周三) 下午2:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jason-li-831202/Vehicle-CV-ADAS] 运行demo.py报错 (Issue #18)




 
Check whether your tensorRT version is compatible with the cuda version.

**Comment by SilaLiu** [comment]
我也是运行了demo.py报错
~/catkin_ws/src/Vehicle-CV-ADAS$ python3 demo.py 
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/pixbus/catkin_ws/src/Vehicle-CV-ADAS/ObjectDetector/yoloDetector.py", line 9, in <module>
    from utils import ObjectModelType, hex_to_rgb, NMS, Scaler
ModuleNotFoundError: No module named 'utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pixbus/catkin_ws/src/Vehicle-CV-ADAS/demo.py", line 7, in <module>
    from taskConditions import TaskConditions, Logger
  File "/home/pixbus/catkin_ws/src/Vehicle-CV-ADAS/taskConditions.py", line 5, in <module>
    from ObjectDetector.utils import CollisionType
  File "/home/pixbus/catkin_ws/src/Vehicle-CV-ADAS/ObjectDetector/__init__.py", line 1, in <module>
    from ObjectDetector.yoloDetector import YoloDetector
  File "/home/pixbus/catkin_ws/src/Vehicle-CV-ADAS/ObjectDetector/yoloDetector.py", line 14, in <module>
    from .utils import ObjectModelType, hex_to_rgb, NMS, Scaler
  File "/home/pixbus/catkin_ws/src/Vehicle-CV-ADAS/ObjectDetector/utils.py", line 4, in <module>
    from numba import jit
  File "/usr/lib/python3/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/lib/python3/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/lib/python3/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

**Comment by SilaLiu** [comment]
这是我的cuda版本：
nvidia-smi
Sat Apr 20 15:21:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        On  | 00000000:01:00.0  On |                  N/A |
| 30%   34C    P8              14W / 170W |    131MiB / 12288MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1395      G   /usr/lib/xorg/Xorg                           78MiB |
|    0   N/A  N/A      1700      G   /usr/bin/gnome-shell                         23MiB |
|    0   N/A  N/A     10782      G   ...seed-version=20240419-130118.436000       18MiB |
+---------------------------------------------------------------------------------------+

**Comment by jason-li-831202** [comment]
https://github.com/jason-li-831202/Vehicle-CV-ADAS/blob/5852d162abf9d3a26a7e42080fc9fc9d2021efbc/ObjectDetector/utils.py#L4

https://github.com/jason-li-831202/Vehicle-CV-ADAS/blob/5852d162abf9d3a26a7e42080fc9fc9d2021efbc/ObjectDetector/utils.py#L130

https://github.com/jason-li-831202/Vehicle-CV-ADAS/blob/5852d162abf9d3a26a7e42080fc9fc9d2021efbc/ObjectDetector/utils.py#L195

Try commenting out the three lines above.

**Comment by SilaLiu** [comment]
我注释了，最后我得到这个结果，我确保我已经安装了，tensorrt

**Comment by 1623021453** [comment]
我可以正常运行demo.py了，我把cuda从11.4换成11.3后可以正常运行了，感谢作者的分享

**Comment by 1623021453** [comment]
> 我注释了，最后我得到这个结果，我确保我已经安装了，tensorrt

作者的代码是在windows下运行的，你是在ubuntu下运行的吗？
