### ISSUE TITLE
Whether there is a train and test code

### ISSUE THREAD

**Issue by nj888-art** [jason-li-831202/Vehicle-CV-ADAS#19]
Hello！I‘m so sorry to bother you. I have an inssue in the project.
If the model not have train code. How the model detect video clips of datasets with different field of view characteristics efficiently ? For example, the model can efficiently detect the lane of this videos, but I  want to use the dataset have the different lane parameter. 
If the model have the train code , Could you tell me where are they?(and the test code also tell me)
How to evaluate model accuracy and detection efficiency?

Thank you very much!

**Comment by jason-li-831202** [comment]
You can refer to the official repository at https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2, which should have a complete training tutorial.

**Comment by nj888-art** [comment]
Thanks for your reply!
