### ISSUE TITLE
qt.qpa.xcb: could not connect to display :.0

### ISSUE THREAD

**Issue by nj888-art** [jason-li-831202/Vehicle-CV-ADAS#20]
I meet an issue when run the demo.py. 
The error was:
qt.qpa.xcb: could not connect to display :.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/nijuan/anaconda3/envs/python3.7/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)

My local computer operating system is windows and I run the code on the remote server Ubuntu os , and then report error like this.Could you tell me the reason about this? Thanks !

**Comment by jason-li-831202** [comment]
If you use cv.imshow() remotely, you need to install extra libraries. You can crawl more related articles.
