### ISSUE TITLE
An error occurred when demo.py was running

### ISSUE THREAD

**Issue by TJW-XMUT** [jason-li-831202/Vehicle-CV-ADAS#22]
![bug](https://github.com/jason-li-831202/Vehicle-CV-ADAS/assets/71960469/29a0726c-6e0b-4000-ad21-ee962d4c47a1)
The following error occurred when running demo.py. How can I solve it? Thank you very much for your reply!

**Comment by jason-li-831202** [comment]
This issue has been merged into Issue #24 .
