### ISSUE TITLE
能否出一个ubuntu版本的

### ISSUE THREAD

**Issue by 1623021453** [jason-li-831202/Vehicle-CV-ADAS#25]

**Comment by jason-li-831202** [comment]
我有用一部分code在ubuntu測試過, 你可以先跑看看, 看有什麼問題

**Comment by 1623021453** [comment]
谢啦，我改了一个ubuntu版本的可以跑通了，是否可以优化下速度，如更换更好的车道线检测算法，现在这个检测速度用不起来



---原始邮件---
发件人: "Kai Chun, ***@***.***&gt;
发送时间: 2024年7月12日(周五) 晚上7:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [jason-li-831202/Vehicle-CV-ADAS] 能否出一个ubuntu版本的 (Issue #25)




 
我有用一部分code在ubuntu測試過, 你可以先跑看看, 看有什麼問題
