### ISSUE TITLE
File "F:\Yolop\Vehicle-CV-ADAS\TrafficLaneDetector\ultrafastLaneDetector\ultrafastLaneDetectorV2.py", line 426, in process_output     return np.array(list(lanes_points.values())), list(lanes_detected.values()) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

### ISSUE THREAD

**Issue by chelsea456** [jason-li-831202/Vehicle-CV-ADAS#9]
i have this error when run demo.py,

**Comment by jason-li-831202** [comment]
Can you print out "lanes_points.values()" and "lanes_detected.values()" to take a look?

**Comment by chelsea456** [comment]
i have slove this prolem, you can share clip original demo

**Comment by Tomhandson1029** [comment]
> i have slove this prolem, you can share clip original demo

can you tell how did you solve this?

**Comment by Tomhandson1029** [comment]
Help??

**Comment by Tomhandson1029** [comment]
> i have slove this prolem, you can share clip original demo

Please let me know, how do you solve the issue
